# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notify' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Messaging'

 
  # Pods for Notify

  target 'Notify-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  end

  target 'NotifyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Notify-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Notify-tvOS

 

end
